name: Auto Release workflow
on:
  push:
    branches: # Accepted PRs on main
      - master
    paths:
      - 'VERSION' # only if version file changed


jobs:
  verify-build:
    uses: ./.github/workflows/build-test.yml

  publish:
    needs: verify-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: echo "Publish to Maven Central"

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: verify-build
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v7
        with:
          name: dist-files # if you dont specify name, it will download all artifacts
          path: dist # if you dont specify path, it will download to root

      - name: FileTree
        run: ls -R

      - name: Read VERSION file
        run: echo "VERSION_TAG=$(cat VERSION | xargs)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION_TAG }}
          #name: Holiday Update #Commercial release name
          files: dist/*
          draft: false
          prerelease: false

