name: Auto Release workflow
on:
  push:
    branches: # Accepted PRs on main
      - master
    paths:
      - 'VERSION' # only if version file changed


jobs:
  verify-build:
    uses: ./.github/workflows/build-test.yml

  publish:
    needs: verify-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo "Publish to Maven Central"

  release:
    runs-on: ubuntu-latest
    needs: verify-build
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v6
        with:
          name: dist-files # if you dont specify name, it will download all artifacts
          path: dist # if you dont specify path, it will download to root
      - name: FileTree
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} #Version tag; inputs.version_tag from UI; or default to ref_name
          #name: Holiday Update #Commercial release name
          files: dist/*
          draft: false
          prerelease: false

