# does nothing, just a trigger extra
name: CI workflow
on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review ] # New, after
    paths-ignore: [ "**.md" ] # Don't run tests if I just fixed a typo in README
  workflow_dispatch: # Adds UI button

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # Cancel previous runs of this workflow for pull requests

jobs:
  build-test:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/build-test.yml

  report:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "All good!"